echo "asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda \
asodjalsdjlasjkdlkasjldkjaslkdjalksjdlajsdlkjaslkdjalksjdlkajfshdkjashakjsdhkajshdkjahsdjkahskjdhakjshdkajshdkahsdkasda"